---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Grok :).
--- DateTime: 2025/12/10 21:49
---

-- Pure Lua Vector3d library (immutable operations return new instances, mutable via set)
local Vector3d = {}
Vector3d.__index = Vector3d

-- Constructor
function Vector3d:new(x, y, z)
    local self = setmetatable({}, Vector3d)
    self.x = x or 0
    self.y = y or 0
    self.z = z or 0
    return self
end

-- Mutable set
function Vector3d:set(arg1, arg2, arg3)
    if type(arg1) == "table" and getmetatable(arg1) == Vector3d then  -- set(other)
        self.x = arg1.x
        self.y = arg1.y
        self.z = arg1.z
    else  -- set(x, y, z)
        self.x = arg1 or 0
        self.y = arg2 or 0
        self.z = arg3 or 0
    end
    return self
end

-- Immutable add
function Vector3d:add(arg1, arg2, arg3)
    expectVector3d(self, "self in add")
    local dx, dy, dz
    if type(arg1) == "table" and getmetatable(arg1) == Vector3d then  -- add(other)
        dx, dy, dz = arg1.x, arg1.y, arg1.z
    else  -- add(dx, dy, dz)
        dx, dy, dz = arg1 or 0, arg2 or 0, arg3 or 0
    end
    return Vector3d:new(self.x + dx, self.y + dy, self.z + dz)
end

-- Immutable sub
function Vector3d:sub(other)
    expectVector3d(self, "self in sub")
    expectVector3d(other, "Expected Vector3d for sub")
    return Vector3d:new(self.x - other.x, self.y - other.y, self.z - other.z)
end

-- Immutable mul (vector or scalar)
function Vector3d:mul(arg)
    expectVector3d(self, "self in mul")
    if type(arg) == "table" and getmetatable(arg) == Vector3d then  -- component-wise mul
        return Vector3d:new(self.x * arg.x, self.y * arg.y, self.z * arg.z)
    else  -- scalar mul
        local scalar = tonumber(arg) or 1
        return Vector3d:new(self.x * scalar, self.y * scalar, self.z * scalar)
    end
end

-- Immutable div (vector or scalar)
function Vector3d:div(arg)
    expectVector3d(self, "self in div")
    if type(arg) == "table" and getmetatable(arg) == Vector3d then  -- component-wise div
        return Vector3d:new(self.x / arg.x, self.y / arg.y, self.z / arg.z)
    else  -- scalar div
        local scalar = tonumber(arg) or 1
        return Vector3d:new(self.x / scalar, self.y / scalar, self.z / scalar)
    end
end

-- Length
function Vector3d:length()
    expectVector3d(self, "self in length")
    return math.sqrt(self.x^2 + self.y^2 + self.z^2)
end

-- Length squared
function Vector3d:lengthSquared()
    expectVector3d(self, "self in lengthSquared")
    return self.x^2 + self.y^2 + self.z^2
end

-- Normalize (returns new)
function Vector3d:normalize()
    expectVector3d(self, "self in normalize")
    local len = self:length()
    if len == 0 then return Vector3d:new(self.x, self.y, self.z) end
    return self:div(len)
end

-- Dot product
function Vector3d:dot(other)
    expectVector3d(self, "self in dot")
    expectVector3d(other, "Expected Vector3d for dot")
    return self.x * other.x + self.y * other.y + self.z * other.z
end

-- Cross product
function Vector3d:cross(other)
    expectVector3d(self, "self in cross")
    expectVector3d(other, "Expected Vector3d for cross")
    return Vector3d:new(
            self.y * other.z - self.z * other.y,
            self.z * other.x - self.x * other.z,
            self.x * other.y - self.y * other.x
    )
end

-- Distance
function Vector3d:distance(other)
    expectVector3d(self, "self in distance")
    expectVector3d(other, "Expected Vector3d for distance")
    return self:sub(other):length()
end

-- Angle
function Vector3d:angle(other)
    expectVector3d(self, "self in angle")
    expectVector3d(other, "Expected Vector3d for angle")
    local dot = self:dot(other)
    local len = self:length() * other:length()
    if len == 0 then return 0 end
    return math.acos(dot / len)
end

-- Negate
function Vector3d:negate()
    expectVector3d(self, "self in negate")
    return Vector3d:new(-self.x, -self.y, -self.z)
end

-- Absolute
function Vector3d:absolute()
    expectVector3d(self, "self in absolute")
    return Vector3d:new(math.abs(self.x), math.abs(self.y), math.abs(self.z))
end

-- Lerp
function Vector3d:lerp(other, t)
    expectVector3d(self, "self in lerp")
    expectVector3d(other, "Expected Vector3d for lerp")
    t = t or 0
    return Vector3d:new(
            self.x + (other.x - self.x) * t,
            self.y + (other.y - self.y) * t,
            self.z + (other.z - self.z) * t
    )
end

-- Min
function Vector3d:min(other)
    expectVector3d(self, "self in min")
    expectVector3d(other, "Expected Vector3d for min")
    return Vector3d:new(
            math.min(self.x, other.x),
            math.min(self.y, other.y),
            math.min(self.z, other.z)
    )
end

-- Max
function Vector3d:max(other)
    expectVector3d(self, "self in max")
    expectVector3d(other, "Expected Vector3d for max")
    return Vector3d:new(
            math.max(self.x, other.x),
            math.max(self.y, other.y),
            math.max(self.z, other.z)
    )
end

-- Type check function
function expectVector3d(value, message)
    if type(value) ~= "table" or getmetatable(value) ~= Vector3d then
        error(message or "Expected Vector3d", 2)
    end
    return value
end

-- Pure Lua Quaterniond library
local Quaterniond = {}
Quaterniond.__index = Quaterniond

-- Constructor
function Quaterniond:new(x, y, z, w)
    local self = setmetatable({}, Quaterniond)
    self.x = x or 0
    self.y = y or 0
    self.z = z or 0
    self.w = w or 1
    return self
end

-- Mutable set
function Quaterniond:set(arg1, arg2, arg3, arg4)
    if type(arg1) == "table" and getmetatable(arg1) == Quaterniond then  -- set(other)
        self.x = arg1.x
        self.y = arg1.y
        self.z = arg1.z
        self.w = arg1.w
    else  -- set(x, y, z, w)
        self.x = arg1 or 0
        self.y = arg2 or 0
        self.z = arg3 or 0
        self.w = arg4 or 1
    end
    return self
end

-- Set from axis-angle (mutable, but returns self)
function Quaterniond:setFromAxisAngle(axis, angle)
    expectVector3d(axis, "Expected Vector3d for axis")
    local halfAngle = angle / 2
    local sin = math.sin(halfAngle)
    self.x = axis.x * sin
    self.y = axis.y * sin
    self.z = axis.z * sin
    self.w = math.cos(halfAngle)
    return self:normalizeInPlace()  -- Normalize mutable
end

-- Immutable add
function Quaterniond:add(other)
    expectQuaterniond(self, "self in add")
    expectQuaterniond(other, "Expected Quaterniond for add")
    return Quaterniond:new(self.x + other.x, self.y + other.y, self.z + other.z, self.w + other.w)
end

-- Immutable mul (quaternion or scalar)
function Quaterniond:mul(arg)
    expectQuaterniond(self, "self in mul")
    if type(arg) == "table" and getmetatable(arg) == Quaterniond then  -- quaternion mul
        return Quaterniond:new(
                self.w * arg.x + self.x * arg.w + self.y * arg.z - self.z * arg.y,
                self.w * arg.y + self.y * arg.w + self.z * arg.x - self.x * arg.z,
                self.w * arg.z + self.z * arg.w + self.x * arg.y - self.y * arg.x,
                self.w * arg.w - self.x * arg.x - self.y * arg.y - self.z * arg.z
        )
    else  -- scalar mul
        local scalar = tonumber(arg) or 1
        return Quaterniond:new(self.x * scalar, self.y * scalar, self.z * scalar, self.w * scalar)
    end
end

-- Length
function Quaterniond:length()
    expectQuaterniond(self, "self in length")
    return math.sqrt(self.x^2 + self.y^2 + self.z^2 + self.w^2)
end

-- Normalize (returns new)
function Quaterniond:normalize()
    expectQuaterniond(self, "self in normalize")
    local len = self:length()
    if len == 0 then return Quaterniond:new(self.x, self.y, self.z, self.w) end
    return Quaterniond:new(self.x / len, self.y / len, self.z / len, self.w / len)
end

-- Mutable normalize
function Quaterniond:normalizeInPlace()
    local len = self:length()
    if len ~= 0 then
        self.x = self.x / len
        self.y = self.y / len
        self.z = self.z / len
        self.w = self.w / len
    end
    return self
end

-- Conjugate (returns new)
function Quaterniond:conjugate()
    expectQuaterniond(self, "self in conjugate")
    return Quaterniond:new(-self.x, -self.y, -self.z, self.w)
end

-- Inverse (returns new)
function Quaterniond:inverse()
    expectQuaterniond(self, "self in inverse")
    local lenSq = self.x^2 + self.y^2 + self.z^2 + self.w^2
    if lenSq == 0 then error("Cannot invert zero quaternion", 2) end
    local invLenSq = 1 / lenSq
    return Quaterniond:new(-self.x * invLenSq, -self.y * invLenSq, -self.z * invLenSq, self.w * invLenSq)
end

-- Transform vector (returns new vector)
function Quaterniond:transform(vec)
    expectQuaterniond(self, "self in transform")
    expectVector3d(vec, "Expected Vector3d for transform")
    local v = Quaterniond:new(vec.x, vec.y, vec.z, 0)
    local res = self:mul(v):mul(self:conjugate())
    return Vector3d:new(res.x, res.y, res.z)
end

-- Slerp (returns new)
function Quaterniond:slerp(other, t)
    expectQuaterniond(self, "self in slerp")
    expectQuaterniond(other, "Expected Quaterniond for slerp")
    t = t or 0
    local dot = self.x * other.x + self.y * other.y + self.z * other.z + self.w * other.w
    local negate = dot < 0
    if negate then dot = -dot end
    local o = negate and Quaterniond:new(-other.x, -other.y, -other.z, -other.w) or other
    if dot > 0.9995 then
        -- Linear interpolation
        local result = Quaterniond:new(
                self.x + t * (o.x - self.x),
                self.y + t * (o.y - self.y),
                self.z + t * (o.z - self.z),
                self.w + t * (o.w - self.w)
        )
        return result:normalize()
    end
    local theta = math.acos(dot)
    local sinTheta = math.sin(theta)
    local scale0 = math.sin((1 - t) * theta) / sinTheta
    local scale1 = math.sin(t * theta) / sinTheta
    return Quaterniond:new(
            self.x * scale0 + o.x * scale1,
            self.y * scale0 + o.y * scale1,
            self.z * scale0 + o.z * scale1,
            self.w * scale0 + o.w * scale1
    )
end

-- Type check function
function expectQuaterniond(value, message)
    if type(value) ~= "table" or getmetatable(value) ~= Quaterniond then
        error(message or "Expected Quaterniond", 2)
    end
    return value
end

-- Module return (for require or direct load)
return {
    Vector3d = Vector3d,
    Quaterniond = Quaterniond,
    expectVector3d = expectVector3d,
    expectQuaterniond = expectQuaterniond
}