# AdvancedPeripherals — Powah SolarPanel integration peripheral

[[method]]
lua = "getStoredEnergy"
ret = "f64"

[[method]]
lua = "getMaxEnergy"
ret = "f64"

[[method]]
lua = "canSeeSky"
ret = "bool"
