//! ミニ Executor — 毎 tick 1 回 Future を poll する。
//! Mini executor — polls the Future once per tick.
//!
//! WASM はシングルスレッドなので、グローバル静的変数で管理して安全。
//! WASM is single-threaded, so it is safe to manage state in global statics.
//!
//! ## ライフサイクル / Lifecycle
//!
//! 1. Java が `wasm_init()` を呼ぶ → [`init`] で main Future を登録
//! 2. Java が毎 tick `wasm_tick()` を呼ぶ → [`tick`] で 1 回 poll
//! 3. `Poll::Ready(())` → main 終了（return 0）
//! 4. `Poll::Pending` → 次 tick まで待機（return 1）
//! 5. panic → panic ハンドラ経由で unreachable（Java が例外キャッチ）

use alloc::boxed::Box;
use core::cell::UnsafeCell;
use core::future::Future;
use core::pin::Pin;
use core::task::{Context, Poll, Waker};

/// Executor の内部状態。
/// Internal executor state.
struct ExecutorInner {
    /// メイン Future（Some = 実行中、None = 未初期化 or 完了）
    /// Main future (Some = running, None = uninitialized or finished)
    future: Option<Pin<Box<dyn Future<Output = ()>>>>,
}

/// グローバル Executor。
/// Global executor.
///
/// WASM はシングルスレッドのため `UnsafeCell` で十分安全。
/// `UnsafeCell` is sufficient because WASM is single-threaded.
struct Executor {
    inner: UnsafeCell<ExecutorInner>,
}

// 安全性: WASM は常にシングルスレッドで実行される。
// Safety: WASM always runs in a single thread.
unsafe impl Sync for Executor {}

/// グローバル Executor インスタンス。
/// Global executor instance.
static EXECUTOR: Executor = Executor {
    inner: UnsafeCell::new(ExecutorInner { future: None }),
};

/// main Future を Executor に登録する。
/// Register the main future with the executor.
///
/// `entry!` マクロ内の `wasm_init()` から呼ばれる。
/// Called from `wasm_init()` generated by the `entry!` macro.
///
/// # 引数 / Arguments
/// - `future`: ユーザーの main 関数が返す Future / the user's main function future
pub fn init(future: impl Future<Output = ()> + 'static) {
    // 安全性: wasm_init は1回だけ呼ばれ、シングルスレッド。
    // Safety: wasm_init is called only once, single-threaded.
    unsafe {
        let inner = &mut *EXECUTOR.inner.get();
        inner.future = Some(Box::pin(future));
    }
}

/// Executor を 1 回 poll する。
/// Poll the executor once.
///
/// `entry!` マクロ内の `wasm_tick()` から呼ばれる。
/// Called from `wasm_tick()` generated by the `entry!` macro.
///
/// # 戻り値 / Return value
/// -  `1`: 継続（Pending） / continue
/// -  `0`: main 正常終了 / main finished
/// - `-1`: Future が登録されていない / no future registered
pub fn tick() -> i32 {
    // 安全性: wasm_tick はシングルスレッドで順次呼ばれる。
    // Safety: wasm_tick is called sequentially, single-threaded.
    unsafe {
        let inner = &mut *EXECUTOR.inner.get();

        let Some(ref mut fut) = inner.future else {
            return -1; // 未初期化 / Not initialized
        };

        // no-op Waker: WASM ではスレッドがないので wake は不要。
        // no-op Waker: no threads in WASM, so wake is unnecessary.
        let waker = Waker::noop();
        let mut cx = Context::from_waker(waker);

        match fut.as_mut().poll(&mut cx) {
            Poll::Pending => 1,     // 継続 / Continue
            Poll::Ready(()) => {
                inner.future = None;
                0                     // main 終了 / Main finished
            }
        }
    }
}
