//! # rust-computers-api
//!
//! RustComputers の Rust 側コアランタイムクレート。
//! Core runtime crate for the Rust side of RustComputers.
//!
//! ## 概要 / Overview
//!
//! Minecraft の WASM コンピューターブロック上で動作する Rust プログラムのための
//! ランタイムライブラリ。`no_std` + `alloc` 環境で async/await を使用可能にする。
//!
//! Runtime library for Rust programs running on Minecraft WASM computer blocks.
//! Enables async/await in a `no_std` + `alloc` environment.
//!
//! ## 使い方 / Usage
//!
//! ```rust,no_run
//! #![no_std]
//! #![no_main]
//! extern crate alloc;
//!
//! use rust_computers_api as rc;
//!
//! rc::entry!(main);
//!
//! async fn main() {
//!     rc::println!("Hello from Rust Computer!");
//!     let line = rc::read_line().await;
//!     rc::println!("You typed: {}", line);
//! }
//! ```

#![no_std]

extern crate alloc;

// モジュール宣言 / Module declarations
pub mod allocator;
pub mod error;
pub mod executor;
pub mod ffi;
pub mod future;
pub mod io;
pub mod msgpack;
pub mod panic;
pub mod peripheral;

// 自動生成ペリフェラルラッパー / Auto-generated peripheral wrappers
// build.rs が peripherals/{group}/*.toml から生成する
// Generated by build.rs from peripherals/{group}/*.toml

// --- CC:Tweaked ---
/// CC:Tweaked ペリフェラル群 / CC:Tweaked peripherals.
pub mod computer_craft {
    /// CC:Tweaked モニター型ラッパー / CC:Tweaked Monitor typed wrapper.
    ///
    /// `peripherals/computer_craft/monitor.toml` を編集して `cargo build` すると再生成される。
    /// Edit `peripherals/computer_craft/monitor.toml` and run `cargo build` to regenerate.
    ///
    /// # 例 / Example
    ///
    /// ```rust,no_run
    /// use rust_computers_api::computer_craft::monitor::Monitor;
    /// use rust_computers_api::peripheral::Direction;
    ///
    /// async fn demo() {
    ///     let mon = Monitor::new(Direction::South);
    ///     let (size, _adv) = rc::parallel!(mon.get_size(), mon.is_advanced()).await;
    ///     let (w, h) = size.unwrap_or((26, 10));
    ///     let _ = mon.clear().await;
    ///     let _ = mon.write(&alloc::format!("Size: {}x{}", w, h)).await;
    /// }
    /// ```
    pub mod monitor { include!(concat!(env!("OUT_DIR"), "/computer_craft__monitor_gen.rs")); }
}

// --- Clockwork CC Compat ---
/// Clockwork CC Compat ペリフェラル群 / Clockwork CC Compat peripherals.
pub mod clockwork {
    pub mod air_compressor { include!(concat!(env!("OUT_DIR"), "/clockwork__air_compressor_gen.rs")); }
    pub mod boiler          { include!(concat!(env!("OUT_DIR"), "/clockwork__boiler_gen.rs")); }
    pub mod coal_burner     { include!(concat!(env!("OUT_DIR"), "/clockwork__coal_burner_gen.rs")); }
    pub mod duct_tank       { include!(concat!(env!("OUT_DIR"), "/clockwork__duct_tank_gen.rs")); }
    pub mod exhaust         { include!(concat!(env!("OUT_DIR"), "/clockwork__exhaust_gen.rs")); }
    pub mod gas_engine      { include!(concat!(env!("OUT_DIR"), "/clockwork__gas_engine_gen.rs")); }
    pub mod gas_network     { include!(concat!(env!("OUT_DIR"), "/clockwork__gas_network_gen.rs")); }
    pub mod gas_nozzle      { include!(concat!(env!("OUT_DIR"), "/clockwork__gas_nozzle_gen.rs")); }
    pub mod gas_pump        { include!(concat!(env!("OUT_DIR"), "/clockwork__gas_pump_gen.rs")); }
    pub mod gas_thruster    { include!(concat!(env!("OUT_DIR"), "/clockwork__gas_thruster_gen.rs")); }
    pub mod gas_valve       { include!(concat!(env!("OUT_DIR"), "/clockwork__gas_valve_gen.rs")); }
    pub mod radiator        { include!(concat!(env!("OUT_DIR"), "/clockwork__radiator_gen.rs")); }
    pub mod redstone_duct   { include!(concat!(env!("OUT_DIR"), "/clockwork__redstone_duct_gen.rs")); }
}

// --- Control-Craft ---
/// Control-Craft ペリフェラル群 / Control-Craft peripherals.
pub mod control_craft {
    pub mod camera                { include!(concat!(env!("OUT_DIR"), "/control_craft__camera_gen.rs")); }
    pub mod dynamic_motor         { include!(concat!(env!("OUT_DIR"), "/control_craft__dynamic_motor_gen.rs")); }
    pub mod flap_bearing          { include!(concat!(env!("OUT_DIR"), "/control_craft__flap_bearing_gen.rs")); }
    pub mod jet                   { include!(concat!(env!("OUT_DIR"), "/control_craft__jet_gen.rs")); }
    pub mod kinematic_motor       { include!(concat!(env!("OUT_DIR"), "/control_craft__kinematic_motor_gen.rs")); }
    pub mod kinetic_resistor      { include!(concat!(env!("OUT_DIR"), "/control_craft__kinetic_resistor_gen.rs")); }
    pub mod link_bridge           { include!(concat!(env!("OUT_DIR"), "/control_craft__link_bridge_gen.rs")); }
    pub mod propeller_controller  { include!(concat!(env!("OUT_DIR"), "/control_craft__propeller_controller_gen.rs")); }
    pub mod slider                { include!(concat!(env!("OUT_DIR"), "/control_craft__slider_gen.rs")); }
    pub mod spinalyzer            { include!(concat!(env!("OUT_DIR"), "/control_craft__spinalyzer_gen.rs")); }
}

// --- Create ---
/// Create ペリフェラル群 / Create peripherals.
pub mod create {
    pub mod nixie_tube       { include!(concat!(env!("OUT_DIR"), "/create__nixie_tube_gen.rs")); }
    pub mod speed_controller { include!(concat!(env!("OUT_DIR"), "/create__speed_controller_gen.rs")); }
    pub mod speed_gauge      { include!(concat!(env!("OUT_DIR"), "/create__speed_gauge_gen.rs")); }
    pub mod station          { include!(concat!(env!("OUT_DIR"), "/create__station_gen.rs")); }
    pub mod stress_gauge     { include!(concat!(env!("OUT_DIR"), "/create__stress_gauge_gen.rs")); }
}

// --- Create Additions ---
/// Create Additions ペリフェラル群 / Create Additions peripherals.
pub mod createaddition {
    pub mod electric_motor       { include!(concat!(env!("OUT_DIR"), "/createaddition__electric_motor_gen.rs")); }
    pub mod modular_accumulator  { include!(concat!(env!("OUT_DIR"), "/createaddition__modular_accumulator_gen.rs")); }
}

// --- AdvancedPeripherals ---
/// AdvancedPeripherals ペリフェラル群 / AdvancedPeripherals peripherals.
pub mod advanced_peripherals {
    pub mod automata_warping  { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__automata_warping_gen.rs")); }
    pub mod beacon            { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__beacon_gen.rs")); }
    pub mod block_reader      { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__block_reader_gen.rs")); }
    pub mod colony_integrator { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__colony_integrator_gen.rs")); }
    pub mod compass           { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__compass_gen.rs")); }
    pub mod energy_detector   { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__energy_detector_gen.rs")); }
    pub mod environment_detector { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__environment_detector_gen.rs")); }
    pub mod geo_scanner       { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__geo_scanner_gen.rs")); }
    pub mod inventory_manager { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__inventory_manager_gen.rs")); }
    pub mod me_bridge         { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__me_bridge_gen.rs")); }
    pub mod nbt_storage       { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__nbt_storage_gen.rs")); }
    pub mod note_block        { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__note_block_gen.rs")); }
    pub mod player_detector   { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__player_detector_gen.rs")); }
    pub mod powah_ender_cell  { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__powah_ender_cell_gen.rs")); }
    pub mod powah_energy_cell { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__powah_energy_cell_gen.rs")); }
    pub mod powah_furnator    { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__powah_furnator_gen.rs")); }
    pub mod powah_magmator    { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__powah_magmator_gen.rs")); }
    pub mod powah_reactor     { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__powah_reactor_gen.rs")); }
    pub mod powah_solar_panel { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__powah_solar_panel_gen.rs")); }
    pub mod powah_thermo      { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__powah_thermo_gen.rs")); }
    pub mod rs_bridge         { include!(concat!(env!("OUT_DIR"), "/advanced_peripherals__rs_bridge_gen.rs")); }
}

// --- Some-Peripherals ---
/// Some-Peripherals ペリフェラル群 / Some-Peripherals peripherals.
pub mod some_peripherals {
    pub mod ballistic_accelerator { include!(concat!(env!("OUT_DIR"), "/some_peripherals__ballistic_accelerator_gen.rs")); }
    pub mod digitizer             { include!(concat!(env!("OUT_DIR"), "/some_peripherals__digitizer_gen.rs")); }
    pub mod radar                 { include!(concat!(env!("OUT_DIR"), "/some_peripherals__radar_gen.rs")); }
    pub mod raycaster             { include!(concat!(env!("OUT_DIR"), "/some_peripherals__raycaster_gen.rs")); }
    pub mod world_scanner         { include!(concat!(env!("OUT_DIR"), "/some_peripherals__world_scanner_gen.rs")); }
}

// 再エクスポート / Re-exports
pub use error::BridgeError;
pub use future::RequestFuture;
pub use io::read_line;

/// エントリーポイントマクロ。
/// Entry-point macro that generates `wasm_init()` and `wasm_tick()` exports.
///
/// # 使い方 / Usage
///
/// ```rust,no_run
/// rc::entry!(main);
///
/// async fn main() {
///     rc::println!("Hello!");
/// }
/// ```
///
/// # 展開後 / Expands to
///
/// ```rust,ignore
/// #[no_mangle]
/// pub extern "C" fn wasm_init() { /* spawn main */ }
/// #[no_mangle]
/// pub extern "C" fn wasm_tick() -> i32 { /* poll executor */ }
/// ```
#[macro_export]
macro_rules! entry {
    ($main_fn:ident) => {
        /// WASM エクスポート: main を executor に登録する。
        /// WASM export: register main with the executor.
        #[no_mangle]
        pub extern "C" fn wasm_init() {
            $crate::executor::init($main_fn());
        }

        /// WASM エクスポート: executor を 1 回 poll する。
        /// WASM export: poll the executor once.
        ///
        /// 戻り値 / Return value:
        /// -  `1` = 継続（Pending） / continue (Pending)
        /// -  `0` = main 正常終了 / main finished normally
        /// - `-1` = panic 発生 / panic occurred
        #[no_mangle]
        pub extern "C" fn wasm_tick() -> i32 {
            $crate::executor::tick()
        }
    };
}

/// 複数の Future を並行して poll する Future を返すマクロ。
/// Macro that returns a Future which polls multiple futures concurrently.
///
/// 2〜4 個の **異なる型** の Future をカンマ区切りで渡す。
/// 返り値は **Future** であり、`.await` で結果のタプルを取得する。
/// どの Future も同一 tick で発行されるため、1 tick 待つだけで全て取得できる。
///
/// Pass 2–4 futures of **potentially different types**, separated by commas.
/// Returns a **Future** that resolves to a tuple of results.
/// All futures are issued in the same tick, so only one tick is consumed.
///
/// ```rust,no_run
/// let (a, b) = rc::parallel!(
///     radar.scan(64.0),
///     sensor.get_temp(),
/// ).await;
/// ```
///
/// ```rust,no_run
/// let (size, is_adv, scale) = rc::parallel!(
///     mon.get_size(),
///     mon.is_advanced(),
///     mon.get_text_scale(),
/// ).await;
/// ```
#[macro_export]
macro_rules! parallel {
    ($a:expr, $b:expr $(,)?) => {
        $crate::future::Join2::new($a, $b)
    };
    ($a:expr, $b:expr, $c:expr $(,)?) => {
        $crate::future::Join3::new($a, $b, $c)
    };
    ($a:expr, $b:expr, $c:expr, $d:expr $(,)?) => {
        $crate::future::Join4::new($a, $b, $c, $d)
    };
}
