//! # rust-computers-api
//!
//! RustComputers の Rust 側コアランタイムクレート。
//! Core runtime crate for the Rust side of RustComputers.
//!
//! ## 概要 / Overview
//!
//! Minecraft の WASM コンピューターブロック上で動作する Rust プログラムのための
//! ランタイムライブラリ。`no_std` + `alloc` 環境で async/await を使用可能にする。
//!
//! Runtime library for Rust programs running on Minecraft WASM computer blocks.
//! Enables async/await in a `no_std` + `alloc` environment.
//!
//! ## 使い方 / Usage
//!
//! ```rust,no_run
//! #![no_std]
//! #![no_main]
//! extern crate alloc;
//!
//! use rust_computers_api as rc;
//!
//! rc::entry!(main);
//!
//! async fn main() {
//!     rc::println!("Hello from Rust Computer!");
//!     let line = rc::read_line().await;
//!     rc::println!("You typed: {}", line);
//! }
//! ```

#![no_std]

extern crate alloc;

// モジュール宣言 / Module declarations
pub mod allocator;
pub mod error;
pub mod executor;
pub mod ffi;
pub mod future;
pub mod io;
pub mod msgpack;
pub mod panic;
pub mod peripheral;

// 自動生成ペリフェラルラッパー / Auto-generated peripheral wrappers
// build.rs が peripherals/*.toml から生成する
// Generated by build.rs from peripherals/*.toml

/// CC:Tweaked モニター型ラッパー / CC:Tweaked Monitor typed wrapper.
///
/// `peripherals/monitor.toml` を編集して `cargo build` すると再生成される。
/// Edit `peripherals/monitor.toml` and run `cargo build` to regenerate.
///
/// # 例 / Example
///
/// ```rust,no_run
/// use rust_computers_api::monitor::Monitor;
/// use rust_computers_api::peripheral::Direction;
///
/// async fn demo() {
///     let mon = Monitor::new(Direction::South);
///     // parallel! で size と is_advanced を 1 tick で同時取得
///     let (size_res, adv_res) = rc::parallel!(mon.get_size(), mon.is_advanced());
///     let (w, h) = size_res.unwrap_or((26, 10));
///     let _ = mon.clear().await;
///     let _ = mon.write(&format!("Size: {}x{}", w, h)).await;
/// }
/// ```
pub mod monitor {
    include!(concat!(env!("OUT_DIR"), "/monitor_gen.rs"));
}

// --- Clockwork CC Compat ---
pub mod clockwork_air_compressor { include!(concat!(env!("OUT_DIR"), "/clockwork_air_compressor_gen.rs")); }
pub mod clockwork_boiler { include!(concat!(env!("OUT_DIR"), "/clockwork_boiler_gen.rs")); }
pub mod clockwork_coal_burner { include!(concat!(env!("OUT_DIR"), "/clockwork_coal_burner_gen.rs")); }
pub mod clockwork_duct_tank { include!(concat!(env!("OUT_DIR"), "/clockwork_duct_tank_gen.rs")); }
pub mod clockwork_exhaust { include!(concat!(env!("OUT_DIR"), "/clockwork_exhaust_gen.rs")); }
pub mod clockwork_gas_engine { include!(concat!(env!("OUT_DIR"), "/clockwork_gas_engine_gen.rs")); }
pub mod clockwork_gas_network { include!(concat!(env!("OUT_DIR"), "/clockwork_gas_network_gen.rs")); }
pub mod clockwork_gas_nozzle { include!(concat!(env!("OUT_DIR"), "/clockwork_gas_nozzle_gen.rs")); }
pub mod clockwork_gas_pump { include!(concat!(env!("OUT_DIR"), "/clockwork_gas_pump_gen.rs")); }
pub mod clockwork_gas_thruster { include!(concat!(env!("OUT_DIR"), "/clockwork_gas_thruster_gen.rs")); }
pub mod clockwork_gas_valve { include!(concat!(env!("OUT_DIR"), "/clockwork_gas_valve_gen.rs")); }
pub mod clockwork_radiator { include!(concat!(env!("OUT_DIR"), "/clockwork_radiator_gen.rs")); }
pub mod clockwork_redstone_duct { include!(concat!(env!("OUT_DIR"), "/clockwork_redstone_duct_gen.rs")); }

// --- Control-Craft ---
pub mod control_craft_dynamic_motor { include!(concat!(env!("OUT_DIR"), "/control_craft_dynamic_motor_gen.rs")); }
pub mod control_craft_jet { include!(concat!(env!("OUT_DIR"), "/control_craft_jet_gen.rs")); }
pub mod control_craft_kinematic_motor { include!(concat!(env!("OUT_DIR"), "/control_craft_kinematic_motor_gen.rs")); }
pub mod control_craft_slider { include!(concat!(env!("OUT_DIR"), "/control_craft_slider_gen.rs")); }
pub mod control_craft_propeller_controller { include!(concat!(env!("OUT_DIR"), "/control_craft_propeller_controller_gen.rs")); }
pub mod control_craft_flap_bearing { include!(concat!(env!("OUT_DIR"), "/control_craft_flap_bearing_gen.rs")); }
pub mod control_craft_kinetic_resistor { include!(concat!(env!("OUT_DIR"), "/control_craft_kinetic_resistor_gen.rs")); }
pub mod control_craft_link_bridge { include!(concat!(env!("OUT_DIR"), "/control_craft_link_bridge_gen.rs")); }
pub mod control_craft_spinalyzer { include!(concat!(env!("OUT_DIR"), "/control_craft_spinalyzer_gen.rs")); }
pub mod control_craft_camera { include!(concat!(env!("OUT_DIR"), "/control_craft_camera_gen.rs")); }

// --- Create ---
pub mod create_speed_gauge { include!(concat!(env!("OUT_DIR"), "/create_speed_gauge_gen.rs")); }
pub mod create_stress_gauge { include!(concat!(env!("OUT_DIR"), "/create_stress_gauge_gen.rs")); }
pub mod create_speed_controller { include!(concat!(env!("OUT_DIR"), "/create_speed_controller_gen.rs")); }
pub mod create_nixie_tube { include!(concat!(env!("OUT_DIR"), "/create_nixie_tube_gen.rs")); }
pub mod create_station { include!(concat!(env!("OUT_DIR"), "/create_station_gen.rs")); }

// --- Create Additions ---
pub mod createaddition_electric_motor { include!(concat!(env!("OUT_DIR"), "/createaddition_electric_motor_gen.rs")); }
pub mod createaddition_modular_accumulator { include!(concat!(env!("OUT_DIR"), "/createaddition_modular_accumulator_gen.rs")); }

// --- AdvancedPeripherals ---
pub mod ap_energy_detector { include!(concat!(env!("OUT_DIR"), "/ap_energy_detector_gen.rs")); }
pub mod ap_environment_detector { include!(concat!(env!("OUT_DIR"), "/ap_environment_detector_gen.rs")); }
pub mod ap_compass { include!(concat!(env!("OUT_DIR"), "/ap_compass_gen.rs")); }
pub mod ap_block_reader { include!(concat!(env!("OUT_DIR"), "/ap_block_reader_gen.rs")); }
pub mod ap_player_detector { include!(concat!(env!("OUT_DIR"), "/ap_player_detector_gen.rs")); }
pub mod ap_inventory_manager { include!(concat!(env!("OUT_DIR"), "/ap_inventory_manager_gen.rs")); }
pub mod ap_colony_integrator { include!(concat!(env!("OUT_DIR"), "/ap_colony_integrator_gen.rs")); }
pub mod ap_beacon { include!(concat!(env!("OUT_DIR"), "/ap_beacon_gen.rs")); }
pub mod ap_note_block { include!(concat!(env!("OUT_DIR"), "/ap_note_block_gen.rs")); }
pub mod ap_powah_energy_cell { include!(concat!(env!("OUT_DIR"), "/ap_powah_energy_cell_gen.rs")); }
pub mod ap_powah_ender_cell { include!(concat!(env!("OUT_DIR"), "/ap_powah_ender_cell_gen.rs")); }
pub mod ap_powah_furnator { include!(concat!(env!("OUT_DIR"), "/ap_powah_furnator_gen.rs")); }
pub mod ap_powah_magmator { include!(concat!(env!("OUT_DIR"), "/ap_powah_magmator_gen.rs")); }
pub mod ap_powah_reactor { include!(concat!(env!("OUT_DIR"), "/ap_powah_reactor_gen.rs")); }
pub mod ap_powah_solar_panel { include!(concat!(env!("OUT_DIR"), "/ap_powah_solar_panel_gen.rs")); }
pub mod ap_powah_thermo { include!(concat!(env!("OUT_DIR"), "/ap_powah_thermo_gen.rs")); }
pub mod ap_rs_bridge { include!(concat!(env!("OUT_DIR"), "/ap_rs_bridge_gen.rs")); }
pub mod ap_automata_warping { include!(concat!(env!("OUT_DIR"), "/ap_automata_warping_gen.rs")); }

// --- Some-Peripherals ---
pub mod sp_raycaster { include!(concat!(env!("OUT_DIR"), "/sp_raycaster_gen.rs")); }
pub mod sp_digitizer { include!(concat!(env!("OUT_DIR"), "/sp_digitizer_gen.rs")); }
pub mod sp_ballistic_accelerator { include!(concat!(env!("OUT_DIR"), "/sp_ballistic_accelerator_gen.rs")); }

// 再エクスポート / Re-exports
pub use error::BridgeError;
pub use future::{JoinAll, RequestFuture};
pub use io::read_line;

/// エントリーポイントマクロ。
/// Entry-point macro that generates `wasm_init()` and `wasm_tick()` exports.
///
/// # 使い方 / Usage
///
/// ```rust,no_run
/// rc::entry!(main);
///
/// async fn main() {
///     rc::println!("Hello!");
/// }
/// ```
///
/// # 展開後 / Expands to
///
/// ```rust,ignore
/// #[no_mangle]
/// pub extern "C" fn wasm_init() { /* spawn main */ }
/// #[no_mangle]
/// pub extern "C" fn wasm_tick() -> i32 { /* poll executor */ }
/// ```
#[macro_export]
macro_rules! entry {
    ($main_fn:ident) => {
        /// WASM エクスポート: main を executor に登録する。
        /// WASM export: register main with the executor.
        #[no_mangle]
        pub extern "C" fn wasm_init() {
            $crate::executor::init($main_fn());
        }

        /// WASM エクスポート: executor を 1 回 poll する。
        /// WASM export: poll the executor once.
        ///
        /// 戻り値 / Return value:
        /// -  `1` = 継続（Pending） / continue (Pending)
        /// -  `0` = main 正常終了 / main finished normally
        /// - `-1` = panic 発生 / panic occurred
        #[no_mangle]
        pub extern "C" fn wasm_tick() -> i32 {
            $crate::executor::tick()
        }
    };
}

/// 複数の Future を並行して待機するマクロ。
/// Macro to await multiple futures concurrently.
///
/// ## タプル構文 / Tuple syntax
///
/// 2〜4 個の Future をタプルとして渡し、結果をタプルで受け取る。
/// どの Future も同一 tick で発行されるため、1 tick 待つだけで全て取得できる。
///
/// Pass 2–4 futures as a tuple and receive results as a tuple.
/// All futures are issued in the same tick, so only 1 tick is consumed.
///
/// ```rust,no_run
/// let (a, b) = rc::parallel!((
///     radar.scan(64.0),
///     sensor.get_temp(),
/// ));
/// ```
///
/// ## Vec 構文 / Vec syntax
///
/// 同一型の Future の Vec を渡し、結果を Vec で受け取る。
/// Pass a Vec of same-typed futures and receive results as a Vec.
///
/// ```rust,no_run
/// let results = rc::parallel!(futures_vec);
/// ```
#[macro_export]
macro_rules! parallel {
    // --- タプル構文 (2〜4 要素) / Tuple syntax (2–4 elements) ---
    (($a:expr, $b:expr $(,)?) $(,)?) => {{
        $crate::future::Join2::new($a, $b).await
    }};
    (($a:expr, $b:expr, $c:expr $(,)?) $(,)?) => {{
        $crate::future::Join3::new($a, $b, $c).await
    }};
    (($a:expr, $b:expr, $c:expr, $d:expr $(,)?) $(,)?) => {{
        $crate::future::Join4::new($a, $b, $c, $d).await
    }};
    // --- Vec 構文 / Vec syntax ---
    ($vec:expr) => {{
        $crate::future::JoinAll::new($vec).await
    }};
}
