# Control-Craft — FlapBearing peripheral

[[method]]
lua = "getAngle"
ret = "f64"

[[method]]
lua = "assembleNextTick"
action = true

[[method]]
lua = "disassembleNextTick"
action = true

[[method]]
lua = "setAngle"
action = true
args = [{ name = "angle", ty = "f64" }]
