---
--- Generated by Gemini
--- DateTime: 2026/02/18
---


local Ballistics = {}

local function atan2(y, x)
    if math.atan2 then return math.atan2(y, x) end
    return math.atan(y, x)
end

local function quatFromAxisAngle(axis, angle)
    local halfAngle = angle * 0.5
    local s = math.sin(halfAngle)
    local w = math.cos(halfAngle)
    -- Assuming normalized axis
    return Quaterniond:new(axis.x * s, axis.y * s, axis.z * s, w)
end

-- ==========================================
-- Matrix3d Implementation
-- ==========================================

local Matrix3d = {}
Matrix3d.__index = Matrix3d

function Matrix3d:new(m00, m01, m02, m10, m11, m12, m20, m21, m22)
    local self = setmetatable({}, Matrix3d)
    self.m00 = m00 or 0; self.m01 = m01 or 0; self.m02 = m02 or 0
    self.m10 = m10 or 0; self.m11 = m11 or 0; self.m12 = m12 or 0
    self.m20 = m20 or 0; self.m21 = m21 or 0; self.m22 = m22 or 0
    return self
end

function Matrix3d:zero()
    self.m00 = 0; self.m01 = 0; self.m02 = 0
    self.m10 = 0; self.m11 = 0; self.m12 = 0
    self.m20 = 0; self.m21 = 0; self.m22 = 0
    return self
end

function Matrix3d:identity()
    self:zero()
    self.m00 = 1
    self.m11 = 1
    self.m22 = 1
    return self
end

function Matrix3d:copy()
    return Matrix3d:new(
        self.m00, self.m01, self.m02,
        self.m10, self.m11, self.m12,
        self.m20, self.m21, self.m22
    )
end

function Matrix3d:determinant()
    return self.m00 * (self.m11 * self.m22 - self.m12 * self.m21) +
           self.m01 * (self.m12 * self.m20 - self.m10 * self.m22) +
           self.m02 * (self.m10 * self.m21 - self.m11 * self.m20)
end

function Matrix3d:invert()
    local det = self:determinant()
    if math.abs(det) < 1e-12 then
        error("Matrix is singular")
    end
    local invDet = 1.0 / det

    local nm00 = (self.m11 * self.m22 - self.m12 * self.m21) * invDet
    local nm01 = (self.m02 * self.m21 - self.m01 * self.m22) * invDet
    local nm02 = (self.m01 * self.m12 - self.m02 * self.m11) * invDet

    local nm10 = (self.m12 * self.m20 - self.m10 * self.m22) * invDet
    local nm11 = (self.m00 * self.m22 - self.m02 * self.m20) * invDet
    local nm12 = (self.m02 * self.m10 - self.m00 * self.m12) * invDet

    local nm20 = (self.m10 * self.m21 - self.m11 * self.m20) * invDet
    local nm21 = (self.m01 * self.m20 - self.m00 * self.m21) * invDet
    local nm22 = (self.m00 * self.m11 - self.m01 * self.m10) * invDet

    return Matrix3d:new(nm00, nm01, nm02, nm10, nm11, nm12, nm20, nm21, nm22)
end

-- ==========================================
-- Math Utilities
-- ==========================================

local function radianReset(angle)
    while angle <= -math.pi do angle = angle + 2 * math.pi end
    while angle > math.pi do angle = angle - 2 * math.pi end
    return angle
end

local function clamp(val, limit)
    return math.max(-limit, math.min(limit, val))
end

-- ==========================================
-- StandardBallisticUtils Implementation
-- ==========================================

local StandardBallisticUtils = {}

function StandardBallisticUtils.dropDistance(t, vy, c, g)
    vy = vy / 20
    t = t * 20
    local a = 1 - c
    local B = g / c
    return (vy - B) * (1 - a^t) / c + B * t
end

function StandardBallisticUtils.flatDistance(v, t, c)
    v = v / 20
    t = t * 20
    local a = 1 - c
    local b = 1
    return b * v * (1 - a^t) / c
end

-- ==========================================
-- Optimizers Implementation
-- ==========================================

local Optimizers = {}

function Optimizers.levenbergMarquardt(func, projector, f_tol, maxIter, x0, y0, z0, tol, lambda, h)
    local x, y, z = x0, y0, z0
    local r = func(x, y, z)
    local m = #r
    local loss = 0
    for _, v in ipairs(r) do loss = loss + v * v end

    local currentLambda = lambda
    local JtJ = Matrix3d:new()
    local Jtr = {0, 0, 0} -- Vector3d or just table

    for iter = 1, maxIter do
        if loss < f_tol then
            return {x = x, y = y, z = z, loss = loss, status = "VALID"}
        end

        local r_xp = func(x + h, y, z)
        local r_xm = func(x - h, y, z)
        local r_yp = func(x, y + h, z)
        local r_ym = func(x, y - h, z)
        local r_zp = func(x, y, z + h)
        local r_zm = func(x, y, z - h)

        if not r_xp or not r_xm or not r_yp or not r_ym or not r_zp or not r_zm then
            return {x = x, y = y, z = z, loss = loss, status = "INVALID"}
        end

        JtJ:zero()
        Jtr[1], Jtr[2], Jtr[3] = 0, 0, 0

        for k = 1, m do
            local j_xk = (r_xp[k] - r_xm[k]) / (2 * h)
            local j_yk = (r_yp[k] - r_ym[k]) / (2 * h)
            local j_zk = (r_zp[k] - r_zm[k]) / (2 * h)
            local val = r[k]

            JtJ.m00 = JtJ.m00 + j_xk * j_xk
            JtJ.m01 = JtJ.m01 + j_xk * j_yk
            JtJ.m02 = JtJ.m02 + j_xk * j_zk

            JtJ.m11 = JtJ.m11 + j_yk * j_yk
            JtJ.m12 = JtJ.m12 + j_yk * j_zk

            JtJ.m22 = JtJ.m22 + j_zk * j_zk

            Jtr[1] = Jtr[1] + j_xk * val
            Jtr[2] = Jtr[2] + j_yk * val
            Jtr[3] = Jtr[3] + j_zk * val
        end
        -- Symmetry
        JtJ.m10 = JtJ.m01
        JtJ.m20 = JtJ.m02
        JtJ.m21 = JtJ.m12

        local improved = false
        for k = 1, 10 do
            local H_damp = JtJ:copy()
            H_damp.m00 = H_damp.m00 + currentLambda
            H_damp.m11 = H_damp.m11 + currentLambda
            H_damp.m22 = H_damp.m22 + currentLambda

            local det = H_damp:determinant()
            if math.abs(det) < 1e-12 then
                currentLambda = currentLambda * 10
            else
                local H_inv = H_damp:invert()
                local dx = -(H_inv.m00 * Jtr[1] + H_inv.m01 * Jtr[2] + H_inv.m02 * Jtr[3])
                local dy = -(H_inv.m10 * Jtr[1] + H_inv.m11 * Jtr[2] + H_inv.m12 * Jtr[3])
                local dz = -(H_inv.m20 * Jtr[1] + H_inv.m21 * Jtr[2] + H_inv.m22 * Jtr[3])

                local px, py, pz = projector(x + dx, y + dy, z + dz)
                
                local r_new = func(px, py, pz)
                local loss_new = 0
                for _, v in ipairs(r_new) do loss_new = loss_new + v * v end

                if loss_new < loss then
                    x, y, z = px, py, pz
                    loss = loss_new
                    r = r_new
                    currentLambda = math.max(1e-7, currentLambda / 10.0)
                    improved = true
                    break
                else
                    currentLambda = currentLambda * 10.0
                end
            end
        end

        if not improved then
             return {x = x, y = y, z = z, loss = loss, status = "VALID"}
        end
    end
    return {x = x, y = y, z = z, loss = loss, status = "VALID"}
end

-- ==========================================
-- Ballistics Implementation
-- ==========================================

function Ballistics.toView(yaw, pitch)
    return Vector3d:new(
        math.cos(pitch) * math.sin(yaw),
        math.sin(pitch),
        math.cos(pitch) * math.cos(yaw)
    )
end



function Ballistics.standardBallisticArray(t, c, g, v0)
    local x = StandardBallisticUtils.flatDistance(v0.x, t, c)
    local z = StandardBallisticUtils.flatDistance(v0.z, t, c)
    local y = StandardBallisticUtils.dropDistance(t, v0.y, c, g)
    return Vector3d:new(x, y, z)
end

-- Factory for Standard Ballistic Trajectory Lambda
-- Returns function(t, v_total_world) -> Vector3d (Displacement from muzzle)
function Ballistics.standardTrajectory(c, g)
    return function(t, v_total)
        -- v_total is the total muzzle velocity vector (including shooter motion)
        return Ballistics.standardBallisticArray(t, c, g, v_total)
    end
end

-- Least Squares Fit for Quadratic Trajectory: p(t) = 0.5 * acc * t^2 + vel * t + pos
-- Returns a function(t) -> Vector3d
function Ballistics.trajectoryLeastSquare(samples)
    local n = #samples
    if n < 3 then
        return Ballistics.trajectoryKinematic(samples)
    end

    local sum_t4, sum_t3, sum_t2, sum_t, sum_1 = 0, 0, 0, 0, n
    local sum_x_t2, sum_x_t, sum_x = 0, 0, 0
    local sum_y_t2, sum_y_t, sum_y = 0, 0, 0
    local sum_z_t2, sum_z_t, sum_z = 0, 0, 0

    for _, sample in ipairs(samples) do
        local t = sample.t
        local p = sample.p
        local t2 = t * t
        local t3 = t2 * t
        local t4 = t3 * t

        sum_t4 = sum_t4 + t4
        sum_t3 = sum_t3 + t3
        sum_t2 = sum_t2 + t2
        sum_t = sum_t + t

        sum_x_t2 = sum_x_t2 + p.x * t2
        sum_x_t = sum_x_t + p.x * t
        sum_x = sum_x + p.x

        sum_y_t2 = sum_y_t2 + p.y * t2
        sum_y_t = sum_y_t + p.y * t
        sum_y = sum_y + p.y

        sum_z_t2 = sum_z_t2 + p.z * t2
        sum_z_t = sum_z_t + p.z * t
        sum_z = sum_z + p.z
    end

    local XTX = Matrix3d:new(
        sum_t4, sum_t3, sum_t2,
        sum_t3, sum_t2, sum_t,
        sum_t2, sum_t, sum_1
    )
    
    local success, inv = pcall(function() return XTX:invert() end)
    if not success then
        return Ballistics.trajectoryKinematic(samples)
    end

    -- Solve for each component
    -- X^T * Y
    local function solve(s_t2, s_t, s_1)
        local a = inv.m00 * s_t2 + inv.m01 * s_t + inv.m02 * s_1
        local b = inv.m10 * s_t2 + inv.m11 * s_t + inv.m12 * s_1
        local c = inv.m20 * s_t2 + inv.m21 * s_t + inv.m22 * s_1
        return a, b, c
    end

    local ax, bx, cx = solve(sum_x_t2, sum_x_t, sum_x)
    local ay, by, cy = solve(sum_y_t2, sum_y_t, sum_y)
    local az, bz, cz = solve(sum_z_t2, sum_z_t, sum_z)

    -- Return predictor function
    return function(t)
        local t2 = t * t
        return Vector3d:new(
            ax * t2 + bx * t + cx,
            ay * t2 + by * t + cy,
            az * t2 + bz * t + cz
        )
    end
end
    

    
-- Predictor: Linear Extrapolation from last sample
-- P(t) = P_last + V_last * t
function Ballistics.trajectoryLinear(samples)
    local last = samples[#samples]
    if not last or not last.v then return nil end
    
    local p0 = last.p
    local v0 = last.v
    local t0 = last.t
    
    return function(t)
        local dt = t  -- Assuming t is relative to "now" (t=0 at last sample). 
                      -- If t is absolute, we need t - t0. 
                      -- The solver usually passes 't' as time-of-flight (future duration).
                      -- So P(t_flight) where t_flight starts at 0.
        return p0:add(v0:mul(dt))
    end
end

-- Predictor: Constant Acceleration Kinematic Fit
-- Estimates acceleration from velocity samples, projects from last state.
-- P(t) = P_last + V_last * t + 0.5 * A_avg * t^2
function Ballistics.trajectoryKinematic(samples)
    local n = #samples
    if n < 2 then return Ballistics.trajectoryLinear(samples) end
    
    -- Estimate acceleration
    -- Simple method: (V_last - V_first) / (t_last - t_first)
    -- Robust method: Least squares on V = A*t + V0 ? 
    -- Or just average of point-to-point accelerations.
    
    -- Let's use (V_last - V_first) / total_time for stability over noise
    local first = samples[1]
    local last = samples[n]
    
    if not first.v or not last.v then return Ballistics.trajectoryLinear(samples) end
    
    local dt_total = last.t - first.t
    if dt_total < 1e-4 then return Ballistics.trajectoryLinear(samples) end
    
    local acc = last.v:sub(first.v):div(dt_total)
    
    local p0 = last.p
    local v0 = last.v
    
    return function(t)
        -- t is time from now
        local t2 = t * t
        return p0:add(v0:mul(t)):add(acc:mul(0.5 * t2))
    end
end

-- Predictor: Circular (Constant Turn Rate)
-- Assumes target assumes constant speed and constant turn rate around an axis perpendicular to velocity.
-- Good for vehicles in a turn.
function Ballistics.trajectoryCircular(samples)
    local n = #samples
    if n < 2 then return Ballistics.trajectoryLinear(samples) end
    
    local last = samples[n]
    local prev = samples[n-1]
    
    if not last.v or not prev.v then return Ballistics.trajectoryLinear(samples) end

    local v0 = last.v
    local p0 = last.p
    local speed = v0:length()
    
    if speed < 1e-3 then return Ballistics.trajectoryLinear(samples) end
    
    -- Estimate turn
    -- Centripetal acceleration direction approx: (V_last - V_prev) normalized
    local dt = last.t - prev.t
    if dt < 1e-4 then return Ballistics.trajectoryLinear(samples) end
    
    local acc_vec = last.v:sub(prev.v):div(dt)
    
    -- Project acc onto perpendicular of V to get turning component
    -- a_n = a - (a . v_hat) * v_hat
    local v_hat = v0:normalize()
    local a_proj_v = v_hat:mul(acc_vec:dot(v_hat))
    local a_normal = acc_vec:sub(a_proj_v)
    
    local a_n_mag = a_normal:length()
    
    if a_n_mag < 0.1 then 
        -- Approx linear
        return Ballistics.trajectoryKinematic(samples)
    end
    
    -- Radius R = v^2 / a_n
    local R = (speed * speed) / a_n_mag
    -- Omega = v / R
    local omega = speed / R
    
    -- Turning axis: k = v x a_n
    local axis = v0:cross(a_normal):normalize()
    
    -- Center of rotation: P0 + (a_normal_hat * R) ? No, a_normal points INWARD.
    -- Center = P0 + (RadiusDirection * R). RadiusDirection is along a_normal.
    -- Wait, acceleration points to center. So Center = P0 + a_normal_hat * R.
    local center = p0:add(a_normal:normalize():mul(R))
    
    -- To predict: Rotate (P0 - Center) by angle (omega * t) around axis, add Center.
    -- Also need to handle component of velocity parallel to axis (helical)? 
    -- For now assume planar turn if we used v x a_n.
    -- But if there was vertical velocity not part of turn?
    -- Simply: V(t) = Rot(V0), P(t) = Integral V(t).
    
    local r0_vec = p0:sub(center) -- Vector from center to P0
    
    return function(t)
        local angle = omega * t
        local qt = quatFromAxisAngle(axis, angle)
        
        -- Rotated position vector relative to center
        local r_t = qt:transform(r0_vec)
        
        -- Add helical drift (velocity component parallel to axis)
        -- V_parallel = (V0 . axis) * axis
        local v_par = axis:mul(v0:dot(axis))
        local drift = v_par:mul(t)
        
        return center:add(r_t):add(drift)
    end
end

function Ballistics.aimPredictLM(
        shooter,        -- { pos, vel, omega, rotation }
        gun,            -- { mount_offset, barrel_length, muzzle_vel }
        target_trajectory,    -- function(t) -> Vector3d (target position at future time t)
        projectile_trajectory,-- function(t, v_total) -> Vector3d (projectile displacement)
        maxIterations, tol, lambda, h
)
    -- Heuristic Initialization
    -- 1. Estimate Target Velocity (Linear Approximation at t=0)
    local p_target_0 = target_trajectory(0)
    local p_target_next = target_trajectory(0.1)
    local v_target_est = p_target_next:sub(p_target_0):div(0.1)
    
    -- 2. Iterative Linear Interception (5 iterations)
    -- Assume constant muzzle velocity and constant target velocity
    local p_muzzle_est_world = shooter.pos:add(shooter.rotation:transform(gun.mount_offset))
    local muzzle_speed = gun.muzzle_vel
    if muzzle_speed < 1.0 then muzzle_speed = 1.0 end
    
    local t_est = 0.1
    local p_aim = p_target_0
    
    for _ = 1, 5 do
        local dist = p_aim:distance(p_muzzle_est_world)
        t_est = dist / muzzle_speed
        -- Update aim point for next iteration based on linear projection
        p_aim = p_target_0:add(v_target_est:mul(t_est))
    end
    
    if t_est < 0.01 then t_est = 0.01 end
    
    -- 3. Calculate Guesses
    local diff = p_aim:sub(p_muzzle_est_world)
    local dir_world_est = diff:normalize()
    local dir_local_est = shooter.rotation:conjugate():transform(dir_world_est)
    
    local yaw_0 = atan2(dir_local_est.x, dir_local_est.z)
    local pitch_0 = math.asin(clamp(dir_local_est.y / (1e-6 + dir_local_est:length()), 1.0))
    local t_0 = t_est

    local function loss(yaw, pitch, t)
        -- 1. Calculate Shooter Kinematics
        local dir_local = Ballistics.toView(yaw, pitch)
        local dir_world = shooter.rotation:transform(dir_local):normalize()
        
        -- Muzzle Position
        local p_pivot_world = shooter.pos:add(shooter.rotation:transform(gun.mount_offset))
        local p_muzzle_world = p_pivot_world:add(dir_world:mul(gun.barrel_length))
        
        -- Muzzle Velocity
        local r_muzzle = p_muzzle_world:sub(shooter.pos)
        local v_tangential = shooter.omega:cross(r_muzzle)
        local v_muzzle_world = shooter.vel:add(v_tangential):add(dir_world:mul(gun.muzzle_vel))
        
        -- 2. Projectile Trajectory
        local displacement = projectile_trajectory(t, v_muzzle_world)
        local p_proj = p_muzzle_world:add(displacement)
        
        -- 3. Target Position
        local p_target = target_trajectory(t)
        
        return {
            p_proj.x - p_target.x,
            p_proj.y - p_target.y,
            p_proj.z - p_target.z
        }
    end

    local function projector(yaw, pitch, t)
        return radianReset(yaw),
               clamp(pitch, math.pi / 2),
               math.max(0.01, t)
    end

    local result = Optimizers.levenbergMarquardt(
        loss, projector, 0, maxIterations, yaw_0, pitch_0, t_0, tol, lambda, h
    )

    if result.status ~= "VALID" then
        return { yaw = yaw_0, pitch = pitch_0, value = t_0, loss = result.loss, status = result.status }
    end
    
    return { yaw = result.x, pitch = result.y, value = result.z, loss = result.loss, status = "VALID" }
end



Ballistics.Matrix3d = Matrix3d
Ballistics.StandardBallisticUtils = StandardBallisticUtils
Ballistics.Optimizers = Optimizers

local ts = 0.01667 -- physics thread

local sampler = {
    k = 5,
    samples = {},
    time = 0,
    push = function (self, p, v)
        self.time = self.time + ts
        table.insert(self.samples, {p = p, v = v, t = self.time})
        while #self.samples > self.k do
            table.remove(self.samples, 1)
        end
    end
}

function define()
    defineInput("t_px")
    defineInput("t_py")
    defineInput("t_pz")
    defineInput("t_vx")
    defineInput("t_vy")
    defineInput("t_vz")

    defineInput("o_bx", 0)
    defineInput("o_by", 2)
    defineInput("o_bz", -4)

    defineInput("l_b", 3)
    defineInput("v_b", 400)

    defineInput("p_c", 0.01)
    defineInput("p_g", -0.025)

    defineInput("s_type", 0)

    defineOutput("yaw")
    defineOutput("pitch")
    defineOutput("loss")
end

local function fetch()
    local qs = Phys.quaternionToWorld()
    local vs = Phys.velocity()
    local ws = Phys.angularVelocity()
    local ps = Phys.position()
    local ob = Vector3d:new(getInput("o_bx"), getInput("o_by"), getInput("o_bz"))
    local lb = getInput("l_b")
    local vb = getInput("v_b")
    local c = getInput("p_c")
    local g = getInput("p_g")
    local vt = Vector3d:new(getInput("t_vx"), getInput("t_vy"), getInput("t_vz"))
    local pt = Vector3d:new(getInput("t_px"), getInput("t_py"), getInput("t_pz"))
    return ps, vs, ws, qs, pt, vt, ob, lb, vb, c, g
end

local function promote(result)
    setOutput("yaw", result.yaw)
    setOutput("pitch", result.pitch)
    setOutput("loss", result.loss)
end

function loop()

    local ps, vs, ws, qs, pt, vt, ob, lb, vb, c, g = fetch()
    sampler:push(pt, vt)
    local shooter = {pos = ps,vel = vs,omega = ws,rotation = qs}
    local gun = {mount_offset = ob, barrel_length = lb, muzzle_vel = vb}
    local predictionFunction = Ballistics.trajectoryLinear(sampler.samples)
    local projectileFunction = Ballistics.standardTrajectory(c, g)
    local result = Ballistics.aimPredictLM(
            shooter, gun,
            predictionFunction, projectileFunction,
            40, 0.1, 1, 1e-6
    )

    promote(result)


end


