---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/12/9 22:09
---


function define()
    defineInput("a")
    defineInput("b")
    defineInput("c")
    defineInput("d")
    defineOutput("x")
    defineOutput("y")
    defineOutput("z")
end


local a = 0
local b = 0
local c = 0
local d = 0

local x = 0
local y = 0
local z = 0

local function fetchInput()
    a = getInput("a")
    b = getInput("b")
    c = getInput("c")
    d = getInput("d")
end

local function updateOutput()
    setOutput("x", x)
    setOutput("y", y)
    setOutput("z", z)
end

function loop()
    fetchInput()
    while true do end
    x = a + b + x
    y = b * c - y
    z = c - d

    updateOutput()
end