# Clockwork CC Compat — Radiator peripheral
# (Map/List戻り値はスキップ)

[[method]]
lua = "getFanType"
ret = "str"

[[method]]
lua = "getFanRPM"
ret = "f64"

[[method]]
lua = "getFanCount"
ret = "i32"

[[method]]
lua = "isActive"
ret = "bool"

[[method]]
lua = "isCooling"
ret = "bool"

[[method]]
lua = "isHeating"
ret = "bool"

[[method]]
lua = "getTargetTemp"
ret = "f64"

[[method]]
lua = "getInputTemperature"
ret = "f64"

[[method]]
lua = "getOutputTemperature"
ret = "f64"

[[method]]
lua = "getThermalFactor"
ret = "f64"

[[method]]
lua = "getAtmosphericPressure"
ret = "f64"

[[method]]
lua = "getPressureScale"
ret = "f64"

[[method]]
lua = "getThermalPower"
ret = "f64"

[[method]]
lua = "getConversionRate"
ret = "f64"
