# Create — Station peripheral

[[method]]
lua = "assemble"
action = true

[[method]]
lua = "disassemble"
action = true

[[method]]
lua = "isTrainPresent"
ret = "bool"

[[method]]
lua = "getStationName"
ret = "str"

[[method]]
lua = "setStationName"
action = true
args = [{ name = "name", ty = "str" }]

[[method]]
lua = "getTrainName"
ret = "str"

[[method]]
lua = "setTrainName"
action = true
args = [{ name = "name", ty = "str" }]

[[method]]
lua = "hasSchedule"
ret = "bool"

[[method]]
lua = "isInAssemblyMode"
ret = "bool"

[[method]]
lua = "setAssemblyMode"
action = true
args = [{ name = "enabled", ty = "bool" }]
